---
- name: Dump storage folder
  hosts: all
  remote_user:  "{{ user }}"
  become: yes

  vars:
    current_realease_path:  "/home/{{ user }}/{{ domain }}/current"

  tasks:
  - name: Include default variables
    include_vars: "{{ playbooks_directory_path }}/variables/default.yml"

  - name: Include variables
    include_vars: "{{ playbooks_directory_path }}/variables/storage.yml"

  - name: Zip host storage folder
    become_user: "{{ remote_default_user }}"
    archive:
      path: "{{ local_storage_folder }}"
      dest: "{{ local_dump_path }}"
      format: zip
    delegate_to: localhost

  # - meta: end_play

  - name: Copy file from remote to host
    copy:
      src: "{{ local_dump_path }}"
      dest: "{{ current_realease_path }}"
      owner: "{{ user }}"
      group: "{{ remote_server_user }}"

  - name: Empty remote storage folder
    file:
      state: absent
      path: "{{ storage_dump_folder }}"

  - name: Create local storage folder
    file:
      state: directory
      path: "{{ storage_dump_folder }}"

  - name: Extract files
    unarchive:
      remote_src: yes
      owner: "{{ remote_server_user }}"
      group: "{{ remote_server_user }}"
      mode: "0775"
      src: "{{ current_realease_path }}/{{ application }}storage.zip"
      dest: "{{ current_realease_path }}/storage/app/"

  - name: Delete remote archive
    file:
      path: "{{ current_realease_path }}/{{ application }}storage.zip"
      state: absent

  - name: Delete host archive
    become_user: "{{ remote_default_user }}"
    file:
      path: "{{ local_dump_path }}"
      state: absent
    delegate_to: localhost
